### ISSUE TITLE
Negative Power of a Number in Clarity

### ISSUE THREAD

**Issue by c0d3rk1d** [stacks-network/stacks-blockchain#3295] opened 2022-09-19 04:42 UTC
**Describe the bug**
Inconsistent power function behavior. 

**Steps To Reproduce**
Open the clarinet console and type

`(pow 0 -2)`
and
`(pow 5 -1)`

**Expected behavior**
`(pow 0 -2)` should return error since it is infinity number and `(pow 5 -1)` should return zero...

**Environment (please complete the following information):**
 - OS: MacOs
 - Clarinet Console 0.33

**Additional context**
<img width="842" alt="Screen Shot 2022-09-19 at 12 26 03 AM" src="https://user-images.githubusercontent.com/43936814/190950800-361b3bf3-3229-4e6d-b9a1-986e23e85538.png">

**Comment by c0d3rk1d** [comment] 2022-09-19 04:47
p.s. I submitted the same issue to [Clarinet Console](https://github.com/hirosystems/clarinet/issues/538) repo.

**Comment by c0d3rk1d** [comment] 2022-09-19 05:06
Similar to `(pow 0 -2)` 

`(log2 0)` is an infinity number, and throws an error...

**Comment by c0d3rk1d** [comment] 2022-09-19 14:15
Here are the test cases... Excell `Power` function vs Clarity `Pow` function

<img width="425" alt="Screen Shot 2022-09-19 at 10 13 23 AM" src="https://user-images.githubusercontent.com/43936814/191038410-5e2ef403-cae2-414c-948e-aecd4b5f00d8.png">

**Comment by c0d3rk1d** [comment] 2022-09-20 18:39
More test data; I have done these tests yesterday, just forgot to post it here.

Base | Power | Clarity | Javascript | Result
-- | -- | -- | -- | --
-5 | -5 | error | 0 | X
-5 | -3 | error | 0 | X
-5 | -1 | error | 0 | X
-5 | 0 | 1 | 1 |  
-5 | 1 | -5 | -5 |  
-5 | 3 | -125 | -125 |  
-5 | 5 | -3125 | -3125 |  
-3 | -5 | error | 0 | X
-3 | -3 | error | 0 | X
-3 | -1 | error | 0 | X
-3 | 0 | 1 | 1 |  
-3 | 1 | -3 | -3 |  
-3 | 3 | -27 | -27 |  
-3 | 5 | -243 | -243 |  
-1 | -5 | error | -1 | X
-1 | -3 | error | -1 | X
-1 | -1 | error | -1 | X
-1 | 0 | 1 | 1 |  
-1 | 1 | -1 | -1 |  
-1 | 3 | -1 | -1 |  
-1 | 5 | -1 | -1 |  
0 | -5 | 0 | Infinity | X
0 | -3 | 0 | Infinity | X
0 | -1 | 0 | Infinity | X
0 | 0 | 1 | 1 |  
0 | 1 | 0 | 0 |  
0 | 3 | 0 | 0 |  
0 | 5 | 0 | 0 |  
1 | -5 | 1 | 1 |  
1 | -3 | 1 | 1 |  
1 | -1 | 1 | 1 |  
1 | 0 | 1 | 1 |  
1 | 1 | 1 | 1 |  
1 | 3 | 1 | 1 |  
1 | 5 | 1 | 1 |  
3 | -5 | error | 0 | X
3 | -3 | error | 0 | X
3 | -1 | error | 0 | X
3 | 0 | 1 | 1 |  
3 | 1 | 3 | 3 |  
3 | 3 | 27 | 27 |  
3 | 5 | 243 | 243 |  
5 | -5 | error | 0 |  
5 | -3 | error | 0 |  
5 | -1 | error | 0 |  
5 | 0 | 1 | 1 |  
5 | 1 | 5 | 5 |  
5 | 3 | 125 | 125 |  
5 | 5 | 3125 | 3125 |

**Comment by jcnelson** [comment] 2022-09-26 15:08
The consensus at the blockchain meeting is that `pow` exhibits well-defined behavior as-is.  The issue is that it was not properly documented.  @obycode will address the documentation.

**Comment by jcnelson** [comment] 2022-10-24 17:50
Docs have been merged, so closing this.

**Closed by jcnelson** 2022-10-24 17:50 UTC
