### ISSUE TITLE
Converting and querying valid `principal` representations

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#2620] opened 2021-04-26 04:38 UTC
There needs to be an extension contract that parses a standard `principal` into its `(buff 20)` and `version` representation, and creates a `principal` from a `version` and `(buff 20)`.  In addition, there should be a way to query the `version` values for mainnet and testnet, and determine whether or not the chain is running on mainnet or testnet.

**Comment by gregorycoppola** [comment] 2021-06-16 14:18
1) What is the "(buff 20)" part of the address called? (We need some kind of name to make the function name.)

2) Regarding

> In addition, there should be a way to query the version values for mainnet and testnet, and determine whether or not the chain is running on mainnet or testnet.

Is this a duplicate of https://github.com/blockstack/stacks-blockchain/issues/2642 ?

Would we just expose a boolean that is like "is-mainnet'?

**Comment by jcnelson** [comment] 2021-06-16 17:22
> What is the "(buff 20)" part of the address called? (We need some kind of name to make the function name.)

It's the hash of one or more public keys.  How about `pubkeyhash`?

> Is this a duplicate of #2642 ?

No.  Here's what I'm thinking:

* An `is-mainnet` global that is `true` if the code is running on mainnet, and false if not. There's already one for `is-regtest`, for example.  Note that depending on how Clarity versioning works, it might be easier to do this as a function instead of a global (I'm not too picky on which).
* A function `is-standard-version` that takes an address version byte as a `(buff 1)` and outputs `true` if the address version byte is _currently_ valid on this chain at all.  So, `(is-standard-version 0x16)` and `(is-standard-version 0x14)` are both true only on mainnet, whereas `(is-standard-version u1a)` and `(is-standard-version 0x15)` are both true only on testnet/regtest.  Right now, since there are no other versions supported, these functions would be false for all other values.

**Comment by gregorycoppola** [comment] 2021-06-17 17:05
With regards to `is-standard-version`, we will already have, from #2642, a function that serves this function given an address.

So, will there really be a case where someone wants to call this on only a byte value, and not on an entire address? What is the use case?

**Comment by jcnelson** [comment] 2021-06-18 06:38
The use-case I had in mind was for constructing a standard `principal` from a `(buff 1)` and a `(buff 20)`, but I realize now that there's not a way to do this in Clarity in the first place.  So I guess we can drop `is-standard-version`.

We definitely need to be able to parse a standard `principal` into its version and pubkeyhash, though.  The main use-case is verifying that a Bitcoin transaction was sent to the same key that owns a Stacks account, and to do that, we'll need to extract the `OP_HASH160` payload from a Bitcoin transaction output and compare it to the pubkeyhash of the principal.  We don't have a way to construct a `principal` from a `(buff 1)` and a `(buff 20)`, so this is the only alternative.

**Comment by njordhov** [comment] 2022-05-04 21:08
The function to get the parts of a principal should have a name reflecting what is returned, such as `principal-parts`, rather than suggesting what the function does to extract the parts (like `parse-principal` or `principal-destruct`). Using a noun rather than a verb for the name of the function would make the code more declarative and avoid creating the misimpression that the principal is mutated.

**Closed** 2022-05-05 19:04 UTC
Labels: consensus-critical, stacks-2.1

**Comment by njordhov** [comment] 2022-05-09 18:53
It is problematic that these proposed functions as implemented will have different responses depending on whether the contract is deployed on testnet or mainnet, responding with an error if the principal to destruct or construct does not match the current network.
