### ISSUE TITLE
[Stacks 2.1] Lack of synthetic event attached to Delegate Stacks STX Bitcoin op 

### ISSUE THREAD

**Issue by lgalabru** [stacks-network/stacks-blockchain#3465] opened 2023-01-03 19:34 UTC
It looks like the stacks-node is not attaching a synthetic event when crafting synthetic transactions created for representing Bitcoin operations performing a delegate Stacks STX.
This synthetic events are essentials for downstream event observers: transactions can't be classified without these, a typical stacks-api node would block its observed stacks-node, resulting in frozen stacks explorers, etc.  
cc @zone117x for confirmation.

**Comment by zone117x** [comment] 2023-01-04 17:25
This is also related to https://github.com/stacks-network/stacks-blockchain/issues/2591

The event data given for Bitcoin-chain stacking ops has never included enough information to generate an accurate TX for regular Stack-STX, but we've never seen anyone complain (lack of usage perhaps?).

**Comment by jcnelson** [comment] 2023-01-04 17:29
This could be added though.  What kind of information do you need?

**Comment by zone117x** [comment] 2023-01-04 17:38
> We can already obtain and return anything you'd get from a normal contract-call to stack-stx (or delegate-stx or stx-transfer?), since that's how the system processes it

Does the system generate a contract-call transaction object that can be serialized like a regular contract-call? If so, simply serializing it and including it in the event payload should give the API enough (along with the associated pox2 print events that the normal txs have).

For reference, the current payloads for these tx types have this null byte property `coreTx.raw_tx === '0x00'`, which the API currently detects, then uses the events associated with the txid to generate a synthetic tx.

**Comment by friedger** [comment] 2023-01-05 20:55
Only delegate-stx is a Bitcoin op, not delegate stacks stx. Isn't it? Is there a synthetic event for delegating STX?

**Comment by janniks** [comment] 2023-01-09 15:44
Where are the available btc ops defined? I can only find [this in SIP-007](https://github.com/stacksgov/sips/blob/0da29c6911c49c45e4125dbeaed58069854591eb/sips/sip-007/sip-007-stacking-consensus.md#stx-operations-on-bitcoin)

**Comment by zone117x** [comment] 2023-01-10 15:44
> Only delegate-stx is a Bitcoin op, not delegate stacks stx. Isn't it?

Yep. The problem is that because these Bitcoin ops are sent to the event-observer with `raw_tx === '0x00'`, the only way to figure out what these txs are supposed to be is by inferring from the associated events. Right now, there are no events associated with the DelegateStx Bitcoin op so it's ignored by the API (and thus won't show up in the explorer and wallets).


> Where are the available btc ops defined? I can only find [this in SIP-007](https://github.com/stacksgov/sips/blob/0da29c6911c49c45e4125dbeaed58069854591eb/sips/sip-007/sip-007-stacking-consensus.md#stx-operations-on-bitcoin) (i.e. `StackStx` and `TransferStx`)

The DelegateStx Bitcoin op was introduced in 2.1, details here: https://github.com/stacksgov/sips/blob/a7f2e58ec90c12ee1296145562eec75029b89c48/sips/sip-015/sip-015-network-upgrade.md#new-burnchain-transaction-delegate-stx

**Comment by pavitthrap** [comment] 2023-01-11 21:24
> This is also related to #2591
> 
> The event data given for Bitcoin-chain stacking ops has never included enough information to generate an accurate TX for regular Stack-STX, but we've never seen anyone complain (lack of usage perhaps?).

Would an adequate solution to this be to add information that allows transactions to be classified more easily? 
I could add a field to the transaction event payload, `burnchain_op`. 

I did something like that in this PR: https://github.com/hirosystems/stacks-subnets/pull/168, and could do that here as well. 

@lgalabru @zone117x

**Comment by pavitthrap** [comment] 2023-01-12 17:07
Providing more context around "synthetic" events in relation to the bitcoin operations. 

The events for the existing btc ops are not synthetic per-se. Transfer stx/ stack stx call the same functions that would be called if they were called as a stacks chain tx. These functions register a STXTransferEvent and STXLockEvent respectively. 
<img width="483" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/14214725/212132867-e88ff675-6548-4b64-91ab-876c76442e5a.png">

However, there is not a distinct STX event type for delegate stx; it is executed as function call in the pox-2 contract. So for there to be an event for this function, I *would* have to create a synthetic transaction. I could create a synthetic print event for it. This solution is perhaps less desirable because then either (a) calls to delegate-stx on the stacks chain would not have a corresponding print events, or (b) I could add synthetic events to calls to delegate-stx from the stacks chain, but that would require some special-casing (there’s already examples special casing for other pox contract calls so not unprecedented). 

To avoid the need for synthetic transactions, I could instead provide more information about btc operations in the transaction event payload. This implementation is also generally useful and satisfies an existing request from the API team.

**Comment by lgalabru** [comment] 2023-01-12 18:49
Personally in favor of adding a new event type (emitted by both native + bitcoin), as I don't see a verbose system being an issue (specially when it comes to STX tokens status) but I'll let @zone117x chime in, as adding new event types to the system could be an issue for the API.

**Comment by friedger** [comment] 2023-01-12 22:14
As a pool admin, I very much like the idea of a new event type that works with stx and btc.
Does it also include revoke delegation?

**Comment by zone117x** [comment] 2023-01-13 15:58
I think it makes sense to just add another synthetic pox-2 contract print event for the `delegate-stx` operation, which gets created regardless of if the operation was from a Bitcoin chain operation or a regular Stacks chain contract-call. This is similar to how the existing `stack-stx` pox-2 print statement works.

At this point I think it makes sense to scope of this issue to only the `delegate-stx` operation (as opposed to tackling a possibly larger issue of improving the event payload for Bitcoin ops in general).

**Comment by pavitthrap** [comment] 2023-01-24 16:13
Addressed in #3503

**Closed by pavitthrap** 2023-01-24 16:13 UTC
Labels: stacks-2.1, must-ship
