### ISSUE TITLE
Execution trace reporting

### ISSUE THREAD

**Issue by zone117x** [stacks-network/stacks-blockchain#1185] opened 2019-12-04 18:27 UTC
_Originally brought up at https://github.com/blockstack/blockstack-core/pull/1117#issuecomment-557745045 -- in the context of generating code coverage reports for the BNS smart contract._

> Would execution tracing be a reasonable thing to implement within the execution cost analysis passes? Seems like the passes already have to do most of the work. 
> 
> The static cost analysis could track each unique "execution unit" (not sure what the correct terminology is -- SIP006 mentions `[unique] Clarity code block`?). 
> 
> These unique execution units could be represented as a flat int array; the size of the array is the count of unique execution units, and the value of each entry is initialized to zero. The runtime analysis would then increment the unique execution unit's value for each actual execution. The map of 
> ```ts
> interface ExecutionTrace {
>   [unique_execution_unit: int]: { 
>     clar_source_char_offset: int; 
>     execution_count: int;
>   }
> }
> ```
> Could then be reported to tooling, which could construct Clarity source code coverage data. 

Reply from @kantai:
> Code coverage would be great to implement ... This would need to be collected via the interpreter, rather than the static analysis, since the static analysis won't know which `if` branches are visited.

**Comment by lgalabru** [comment] 2020-02-13 16:02
Building on top of this idea, we could also associate cost associated to the evaluation of each expression, and produce a really good UX helping developers understanding costs (from the explorer or other tooling).

**Comment by zone117x** [comment] 2020-08-12 21:22
Bump (not stale IMO)

**Comment by kantai** [comment] 2021-02-09 14:24
This would still be a useful feature for the Clarity VM.

**Comment by CharlieC3** [comment] 2021-05-24 16:29
Is this issue a duplicate of https://github.com/blockstack/stacks-blockchain/issues/1818 ?

**Comment by kantai** [comment] 2021-05-24 16:31
Not exactly -- I think this is _closest_ to #2592

**Comment by jcnelson** [comment] 2023-02-22 05:26
Temporarily assigning to @obycode for now.   Please re-assign as appropriate.

**Comment by kantai** [comment] 2023-02-22 14:36
Code coverage has been implemented in the Clarity VM. Both the clarity-cli and clarinet are capable of reporting code coverage.

**Closed by kantai** 2023-02-22 14:36 UTC
Labels: clarity, back-burner
