### ISSUE TITLE
[Clarity] Escaped backslash in strings may fail parsing

### ISSUE THREAD

**Issue by njordhov** [stacks-network/stacks-blockchain#3123] opened 2022-05-01 20:33 UTC
**Describe the bug**

Parsing a string with escaped backslash `\\` sometimes fails with error.

**Steps To Reproduce**

Evaluate in the Clarity repl:
`(list "\\" "x")`
=> `error: Expected whitespace or a close parens. Found: 'x'`

A contract with the code above also fails to deploy on testnet.

**Expected behavior**

Strings with an escaped backslash should parse correctly.

Note that the expression parses if the `"x"` is removed. Evaluate in the Clarity repl:

 `(list "\\")`
=> `["\\"]`

**Environment (please complete the following information):**

Confirmed in the latest Clarity REPL and by deploying to Testnet.

**Comment by obycode** [comment] 2022-05-02 20:45
The problem is in this regular expression from [vm/ast/parser/mod.rs:140](https://github.com/stacks-network/stacks-blockchain/blob/59363a2dca5277bc01646bebcab98909c955bee1/src/vm/ast/parser/mod.rs#L139-L142):

```
        LexMatcher::new(
            r##""(?P<value>((\\")|([[ -~]&&[^"]]))*)""##,
            TokenType::StringASCIILiteral,
        ),
```

For the ascii string in the example, `(list "\\" "x")`, the first token in the list from the lever is the string `"\\\" "`.

We have the improved parser v2 in the REPL which handles this correctly. 2.1 seems like a good time to switch the canonical VM over to use this new parser. Should I begin putting together a PR for that?

**Comment by jcnelson** [comment] 2022-08-03 23:36
Closing as complete if this was fixed in the new v2 parser.  Please reopen if not.

**Closed by jcnelson** 2022-08-03 23:36 UTC
Labels: consensus-critical, stacks-2.1

**Comment by njordhov** [comment] 2022-08-04 07:14
Is there a unit test to validate it has been fixed for the v2 parser?

**Comment by obycode** [comment] 2022-08-04 14:29
No, I don't think there is. You're right, we should add tests for these.

**Comment by njordhov** [comment] 2022-08-04 17:11
There should also be tests for related cases that parses but shouldn't, such as:

```clarity
(list "\\" x")
```
