### ISSUE TITLE
Node is doing discovery on private subnets

### ISSUE THREAD

**Issue by pseudozach** [stacks-network/stacks-blockchain#3429] opened 2022-12-04 23:52 UTC
Hi,
I'm running a node for lnswap and the infrastructure provider is complaining that node is doing discovery on private subnets.
is this normal? can it be avoided? is there config switch I can use to stop this traffic?

ps: I've tried using firewall unsuccessfully, would rather solve the root cause.

>##########################################################################
>#               Netscan detected from host   xxx.23               #
>##########################################################################
time                protocol src_ip src_port          dest_ip dest_port
>Sat Dec  3 09:24:40 2022 TCP   xxx.23  36814 =>       10.0.1.12 20444
Sat Dec  3 09:24:47 2022 TCP   xxx.23  36814 =>       10.0.1.12 20444
Sat Dec  3 09:28:12 2022 TCP   xxx.23  43576 =>       10.0.3.91 20444
Sat Dec  3 09:28:12 2022 TCP   xxx.23  50020 =>        10.0.6.7 20444
Sat Dec  3 09:24:40 2022 TCP   xxx.23  51800 =>       10.0.6.11 20444
Sat Dec  3 09:24:47 2022 TCP   xxx.23  51800 =>       10.0.6.11 20444

**Comment by jcnelson** [comment] 2022-12-05 15:27
> I'm running a node for lnswap and the infrastructure provider is complaining that node is doing discovery on private subnets.
is this normal? can it be avoided? is there config switch I can use to stop this traffic?

Can you provide some debug logs and your config file (with any private keys omitted)?

**Comment by wileyj** [comment] 2022-12-05 16:16
> Hi, I'm running a node for lnswap and the infrastructure provider is complaining that node is doing discovery on private subnets. is this normal? can it be avoided? is there config switch I can use to stop this traffic?
> 
> ps: I've tried using firewall unsuccessfully, would rather solve the root cause.
> 
> > ##########################################################################
> > # Netscan detected from host   xxx.23
> > ##########################################################################
> > time                protocol src_ip src_port          dest_ip dest_port
> > Sat Dec  3 09:24:40 2022 TCP   xxx.23  36814 =>       10.0.1.12 20444
> > Sat Dec  3 09:24:47 2022 TCP   xxx.23  36814 =>       10.0.1.12 20444
> > Sat Dec  3 09:28:12 2022 TCP   xxx.23  43576 =>       10.0.3.91 20444
> > Sat Dec  3 09:28:12 2022 TCP   xxx.23  50020 =>        10.0.6.7 20444
> > Sat Dec  3 09:24:40 2022 TCP   xxx.23  51800 =>       10.0.6.11 20444
> > Sat Dec  3 09:24:47 2022 TCP   xxx.23  51800 =>       10.0.6.11 20444

Can you share details on the firewall setup that you tried? 
i don't think we should change the blockchain code to only try to discover nodes over the public internet (in some cases, it's advantageous to also look over private networks).

**Comment by wileyj** [comment] 2022-12-05 18:17
hmm, the only way that might tell us something is to modify the command line /args for the blockchain so it's DEBUG logging.
in your .env `STACKS_LOG_DEBUG=1` should do it with a restart. 

the ordering of your rules and the rules look correct, but i'm not entirely familiar with how ufw works so i'll have to read the docs. i may try to reproduce this myself as well. 

one other thing to note - there was new version released, so you'll want to update this: `STACKS_BLOCKCHAIN_VERSION=2.05.0.5.0` to `STACKS_BLOCKCHAIN_VERSION=2.05.0.6.0`

**Comment by wileyj** [comment] 2022-12-05 18:21
I have a feeling this is somehow related to how docker (used by the repo you're running) modifies iptables. 
https://github.com/chaifeng/ufw-docker

i'll see what happens when i attempt to reproduce it, but the reasoning in this article makes sense with a cursory glance.

**Comment by pseudozach** [comment] 2022-12-05 22:19
no, it's a debian VM and I'm not aware of any other external firewalls. What I'm told is that, once traffic leaves my VM it hits their router which is where they do this netscan and detect the erroneous p2p traffic.

**Comment by wileyj** [comment] 2022-12-08 05:17
Been testing out some options tonight, i think i've found something **easy** that'll work:

## Test setup
- external stacks-blockchain host at `10.0.102.244`
- testing host at: `10.0.102.121`
- Debian 10 VM
- netcat uses a 10s timeout
- both hosts running the containers (with port 80 proxy)  from https://github.com/stacks-network/stacks-blockchain-docker
- cwd: `/home/admin/stacks-blockchain-docker`

## Steps
1. Test connection from testing host->external host over `20443` and `20444`:
```bash
# from testing host to external host on 20443
$ nc -vz -w 10 10.0.102.244 20443
external [10.0.102.244] 20443 (?) open
# from testing host to external host on 20444
$ nc -vz -w 10 10.0.102.244 20444
external [10.0.102.244] 20444 (?) open
# curl external host /v2/info on 20443
$ curl -sL 10.0.102.244:20443/v2/info | jq .stacks_tip_height
86289
```
2. stop all containers, i.e. `./manage.sh -n mainnet -a stop`
3. edit docker opts: 
```bash
sudo bash -c 'echo DOCKER_OPTS=\"--iptables=false\" >> /etc/default/docker' 
```
4. restart docker: 
```bash
systemctl restart docker
```
5. restart containers, i.e. `./manage.sh -n mainnet -a start -f proxy`
6. deny outbound connections on `20444` and enable ufw
```bash
sudo ufw deny out 20444/tcp
sudo ufw enable
```
7. retest connection from step 1:
```bash
$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
20444/tcp                  DENY OUT    Anywhere                  
20444/tcp (v6)             DENY OUT    Anywhere (v6) 

# from testing host to external host on 20443
$ nc -vz -w 10 10.0.102.244 20443
external [10.0.102.244] 20443 (?) open
# from testing host to external host on 20444
$ nc -vz -w 10 10.0.102.244 20444
external [10.0.102.244] 20444 (?) : Connection timed out
# from testing host to itself on 20444
$ nc -vz -w 10 localhost 20444 
localhost [127.0.0.1] 20444 (?) open
# curl external host /v2/info on 20443
$ curl -sL 10.0.102.244:20443/v2/info | jq .stacks_tip_height
86289
```


based on the setup you've shared, you may need to tweak your firewall rules a little bit or adjust them so the ports you need open still are, but i'm hopeful this will resolve the issue with your provider.

**Comment by wileyj** [comment] 2022-12-08 05:20
ahh nuts. disregard the above - i'm still able to hit my external host *from* the container itself. my mistake was testing the connection from the VM only. 
I'll keep poking at this

**Comment by wileyj** [comment] 2022-12-08 19:07
The one thing to consider here is that the rules won't persist on reboot. There are some ways to accomplish this, but in my testing the *easy* way isn't possible because it reorders the list of the saved rules (i.e. the DROP rule  is lower in the chain, so it's overridden). 

## add iptables rules
```bash
sudo iptables -I FORWARD -p tcp --dport 20444 -j DROP  # block outgoing 20444 from container
sudo iptables -A OUTPUT -p tcp --dport 20444 -j DROP   # block outgoing 20444 from VM
```

## delete rules
```bash
sudo iptables -D FORWARD -p tcp --dport 20444 -j DROP # block outgoing 20444 from container
sudo iptables -D OUTPUT -p tcp --dport 20444 -j DROP  # block outgoing 20444 from VM
```

```bash
sudo apt install iptables-persistent         # install tool to keep iptables rules persistent across reboots
sudo iptables-save -f /etc/iptables/rules.v4 # save current rules
sudo systemctl enable netfilter-persistent   # enable reloading rules on reboot
```


## manual reload
```bash
sudo netfilter-persistent reload
```


_normally_  `netfilter-persistent` should reload all the rules, but in my testing the order was incorrect so i had to add a startup script to my VM to load the rules manually on reboot. 


with the DROP rules enabled (like in your previous reply), this will drop all outgoing on port `20444` from both containers and the VM

**Comment by wileyj** [comment] 2022-12-08 19:17
Closing this - seems like we have a solution. reopen if need some more help on this though

**Closed by wileyj** 2022-12-08 19:17 UTC
