### ISSUE TITLE
Optimize mempool walk to speed up miner loop by ~6x

### ISSUE THREAD

**Issue by gregorycoppola** [stacks-network/stacks-blockchain#3229] opened 2022-08-01 14:10 UTC
**Is your feature request related to a problem? Please describe.**
From profiling experiments, it looks like there is an opportunity to save a lot of time in the inner miner running loop.

In general, we find that over 85% of the time spent in the miner loop is spent picking the next transaction, in `MemPoolDB::get_next_tx_to_consider`, and only around 15% of time is spent actually processing transactions. This suggests that, if this time could be reduced near zero, the speed of the inner loop could be increased by around 6x.

For example, here is an example line from a mock-miner running on GCP with the special logging PR https://github.com/stacks-network/stacks-blockchain/pull/3224:

```
INFO [1659067157.220537] [src/core/mempool.rs:1148] [relayer] total_inside_time: 2.143321953s total_outside_time: 16.914410382s total_consider_next_time: 15.77858194s total_update_nonce_time: 1.062061107s total_bump_nonce_time: 71.12287ms
```

We see that, for `2.1s` processing transactions, `16.9s` were spent picking the next transaction to process, with `15.8s` spent in `consider_next_transaction` and another `1.1s` updating nonces.

I uploaded a relevant sample of the logs from one mock miner. [depict-outside-time2.txt](https://github.com/stacks-network/stacks-blockchain/files/9234525/depict-outside-time2.txt)

Statistics computed from these logs show that, for loops where the miner loop takes over `10s`, over 86% of the time is spent outside of transaction processing.

These results have been replicated using out-of-the-box settings on: 1) a Dell lap top, 2) a GCP machine, 3) a AWS machine.

**Describe the solution you'd like**
Create some optimized MemPoolDB data structure that bring to near 0 the cost of picking a new transaction.

Also, this structure should efficiently solve:
* https://github.com/stacks-network/stacks-blockchain/issues/3188
* https://github.com/stacks-network/stacks-blockchain/issues/3193

**Describe alternatives you've considered**
#3225 shows that we can actually realize the gains described by "pre-caching" the mempool walk. However, this pre-caching itself takes time, and can become invalid https://discord.com/channels/621759717756370964/730814571517968436/1002698396928311378

**Additional context**
* https://github.com/stacks-network/stacks-blockchain/issues/3188
* https://github.com/stacks-network/stacks-blockchain/issues/3193

**Comment by jcnelson** [comment] 2022-08-08 15:23
Per @igorsyl:

* When there are thousands of transactions, `perf` indicates that 50% of the time is spent in `libsqlite3`
* Added `tip_mine` subcommand to try building off of an arbitrary chain tip, for the purposes of building a large block with lots of mempool transactions 
* Working on a reproducible benchmark test harness 
* A current limitation is that `sqlite3` will do a scan of some kind due to the `WHERE`-clauses having variable arguments (so indexes alone won't help us)
* Looking into batch queries against the mempool to remedy the above.

Per the blockchain meeting:

* There exists a way to store each tx in the chainstate as a separate table, to facilitate benchmarking.
* We're effectively maintaining a min-heap in the mempool, but we don't precompute the rank of each row (we do it dynamically).  We could maintain the heap invariant on insert, which should make each query to `get_next_tx_to_consider` an O(1) operation (modulo b-tree walking)
* Can also try loading a batch of mempool transactions into RAM

**Comment by jcnelson** [comment] 2022-11-16 04:54
I think the core of this issue is now addressed -- the mempool miner loop is much, much faster.  Gonna go ahead and close this.

**Closed by jcnelson** 2022-11-16 04:54 UTC
