### ISSUE TITLE
Missing multiple BTC blocks (only 1 stx bloock in 6 btc blocks)

### ISSUE THREAD

**Issue by Hero-Gamer** [stacks-network/stacks-blockchain#3631] opened 2023-03-23 14:10 UTC
**Describe the bug**
In the past hour, there was only 1 anchor block in 6 btc blocks 

**Steps To Reproduce**
N/A

**Expected behavior**
Close to 1:1. 

**Environment (please complete the following information):**
<img width="467" alt="image" src="https://user-images.githubusercontent.com/92864860/227228389-0b4cb210-122a-4770-94e2-d40bbf2e1367.png">
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/92864860/227228416-3c2b0955-2a00-4b35-bdca-02e8b37b0cf0.png">

**Additional context**
Don't know if it's related to the recent MEV or just nodes not upgrading to Stacks 2.1. 
Minutes were several minutes apart at least between each BTC block.
Just raising awareness after user reporting.

**Comment by Hero-Gamer** [comment] 2023-03-23 15:04
<img width="551" alt="image" src="https://user-images.githubusercontent.com/92864860/227245362-c6851009-baf3-4543-843b-1c57cc6fd392.png">
I wonder if it has anything to do with this instance.

Full tweet here: https://twitter.com/bitmexresearch/status/1638875082943520769

**Comment by 314159265359879** [comment] 2023-03-23 15:53
This looks like an extreme case. Thanks for reporting it. Bitcoin forking usually plays a role.

I believe expected behavior does deviate from 1:1 it is more like 9:10 where 95% is the target. Completely avoiding flashblocks is not possible as I understand.

Stacks not anchoring looks more common when Bitcoin blocks are fast. Average times are 9.37 min per block recently. Could play a role too. 
![image](https://user-images.githubusercontent.com/33360391/227259331-ba705450-9aff-4c0e-8db5-1d7416e12eb5.jpeg)

**Comment by kantai** [comment] 2023-03-28 19:28
These weren't actually missed blocks -- this was just a long-ish reorg. We can see some reorgs/forks occurring with some regularity in the mainnet chain at the moment, but I don't think is specifically a issue for this repo. There is ongoing discussion on the Stacks forum and discussion topics on this repo about related challenges in mining:

* https://forum.stacks.org/t/rfc-minimum-bid-pox-to-thwart-bitcoin-mev/14675
* https://github.com/stacks-network/stacks/discussions/468#discussioncomment-5055463

And so I'm closing this issue in favor of continuing the discussions in those forums.

**Closed by kantai** 2023-03-28 19:28 UTC
